ktor:
  application:
    modules:
      - idv.maxence.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "my-domain"
  audience: "user"
  realm: "Social Media"
  secret: my-secret
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password